version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_USER: alfi
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: chatboot
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - 3303:3306
    volumes:
      - ./mysql-data:/var/lib/mysql    
    networks:
      springboot-mysql-net:

  springboot-restful-webservices:
    container_name: chatboot
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - 5173:5173
    depends_on:
      - mysqldb
    environment:  
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/chatboot
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: